# Generated by Django 5.2.6 on 2025-09-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_visit',
            new_name='last_active',
        ),
    ]
