# Generated by Django 5.2.6 on 2025-09-11 14:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['brand'],
                'indexes': [models.Index(fields=['brand'], name='main_carbra_brand_f08fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.carbrand')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'model',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_catego_name_5111b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік випуску')),
                ('type', models.CharField(choices=[('Any', 'Будь-який'), ('Cars', 'Легкові'), ('Moto', 'Мото'), ('Trucks', 'Вантажівки'), ('Trailers', 'Причепи'), ('Special', 'Спецтехніка'), ('Agro', 'Сільгосптехніка'), ('Buses', 'Автобуси'), ('Water', 'Водний транспорт'), ('Air', 'Повітряний транспорт'), ('Campers', 'Автобудинки')], max_length=255, verbose_name='Тип машини')),
                ('slug', models.SlugField(max_length=255)),
                ('region', models.CharField(choices=[('Vinnytsia', 'Вінницька обл.'), ('Lutsk', 'Волинська обл.'), ('Dnipro', 'Дніпропетровська обл.'), ('Donetsk', 'Донецька обл.'), ('Zhytomyr', 'Житомирська обл.'), ('Uzhhorod', 'Закарпатська обл.'), ('Zaporizhzhia', 'Запорізька обл.'), ('Ivano-frankivsk', 'Івано-Франківська обл.'), ('Kyiv', 'Київська обл.'), ('Kropyvnytskyi', 'Кіровоградська обл.'), ('Luhansk', 'Луганська обл.'), ('Lviv', 'Львівська обл.'), ('Mykolaiv', 'Миколаївська обл.'), ('Odesa', 'Одеська обл.'), ('Poltava', 'Полтавська обл.'), ('Rivne', 'Рівненська обл.'), ('Sumy', 'Сумська обл.'), ('Ternopil', 'Тернопільська обл.'), ('Kharkiv', 'Харківська обл.'), ('Kherson', 'Херсонська обл.'), ('Khmelnytskyi', 'Хмельницька обл.'), ('Cherkasy', 'Черкаська обл.'), ('Chernivtsi', 'Чернівецька обл.'), ('Chernihiv', 'Чернігівська обл.'), ('Simferopol', 'АР Крим')], max_length=255, verbose_name='Область')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('color', models.CharField(blank=True, choices=[('white', 'Білий'), ('pearl_white', 'Перламутровий білий'), ('snow_white', 'Сніжно-білий'), ('arctic_white', 'Арктичний білий'), ('ivory_white', 'Молочний'), ('black', 'Чорний'), ('jet_black', 'Глибокий чорний'), ('obsidian_black', 'Обсидіановий чорний'), ('midnight_black', 'Опівнічний чорний'), ('phantom_black', 'Фантомний чорний'), ('gray', 'Сірий'), ('silver', 'Сріблястий'), ('gunmetal', 'Графітовий'), ('space_grey', 'Космічний сірий'), ('steel_grey', 'Стальний сірий'), ('charcoal', 'Антрацитовий'), ('blue', 'Синій'), ('navy_blue', 'Темно-синій'), ('deep_blue', 'Насичений синій'), ('light_blue', 'Блакитний'), ('sapphire_blue', 'Сапфіровий синій'), ('sky_blue', 'Небесно-блакитний'), ('red', 'Червоний'), ('bright_red', 'Яскраво-червоний'), ('burgundy', 'Бордовий'), ('wine_red', 'Винний червоний'), ('candy_red', 'Карамельний червоний'), ('crimson', 'Малиновий'), ('green', 'Зелений'), ('emerald_green', 'Смарагдовий зелений'), ('olive_green', 'Оливковий'), ('forest_green', 'Лісовий зелений'), ('dark_green', 'Темно-зелений'), ('yellow', 'Жовтий'), ('sport_yellow', 'Спортивний жовтий'), ('sunflower', 'Соняшниковий'), ('lemon', 'Лимонний'), ('mustard_yellow', 'Гірчичний жовтий'), ('orange', 'Помаранчевий'), ('burnt_orange', 'Вигорілий помаранчевий'), ('sunset_orange', 'Захід сонця'), ('copper', 'Мідний'), ('amber', 'Бурштиновий'), ('brown', 'Коричневий'), ('bronze', 'Бронзовий'), ('mocha', 'Мокко'), ('coffee_brown', 'Кавовий'), ('chocolate_brown', 'Шоколадний'), ('gold', 'Золотий'), ('champagne', 'Шампанське'), ('gold_metallic', 'Металік золото'), ('sand_gold', 'Піщано-золотий'), ('purple', 'Фіолетовий'), ('dark_purple', 'Темно-фіолетовий'), ('lavender', 'Лавандовий'), ('plum', 'Сливовий'), ('amethyst', 'Аметистовий'), ('pink', 'Рожевий'), ('hot_pink', 'Яскраво-рожевий'), ('light_pink', 'Ніжно-рожевий'), ('magenta', 'Малиново-рожевий'), ('fuchsia', 'Фуксія'), ('beige', 'Бежевий'), ('cream', 'Кремовий'), ('ivory', 'Слонова кістка'), ('sand', 'Піщаний'), ('khaki', 'Хакі'), ('matte_black', 'Матово-чорний'), ('matte_grey', 'Матово-сірий'), ('matte_blue', 'Матово-синій'), ('matte_red', 'Матово-червоний'), ('pearl', 'Перламутровий'), ('pearl_blue', 'Перламутровий синій'), ('pearl_green', 'Перламутровий зелений'), ('pearl_red', 'Перламутровий червоний'), ('chameleon', 'Хамелеон'), ('rainbow', 'Райдужний'), ('holographic', 'Голографічний')], max_length=255, null=True, verbose_name='Кольори')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.category')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['model'], name='main_carmod_model_47b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['id', 'slug'], name='main_cars_id_bfcaef_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['model'], name='main_cars_model_i_9af7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['-created'], name='main_cars_created_d5508e_idx'),
        ),
    ]
