# Generated by Django 5.2.6 on 2025-09-09 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['brand'],
                'indexes': [models.Index(fields=['brand'], name='main_carbra_brand_f08fdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.carbrand')),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'model',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='main_catego_name_5111b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Рік випуску')),
                ('type', models.CharField(choices=[('Any', 'Будь-який'), ('Cars', 'Легкові'), ('Moto', 'Мото'), ('Trucks', 'Вантажівки'), ('Trailers', 'Причепи'), ('Special', 'Спецтехніка'), ('Agro', 'Сільгосптехніка'), ('Buses', 'Автобуси'), ('Water', 'Водний транспорт'), ('Air', 'Повітряний транспорт'), ('Campers', 'Автобудинки')], max_length=255, verbose_name='Тип машини')),
                ('slug', models.SlugField(max_length=255)),
                ('region', models.CharField(choices=[('Vinnytsia', 'Вінницька обл.'), ('Lutsk', 'Волинська обл.'), ('Dnipro', 'Дніпропетровська обл.'), ('Donetsk', 'Донецька обл.'), ('Zhytomyr', 'Житомирська обл.'), ('Uzhhorod', 'Закарпатська обл.'), ('Zaporizhzhia', 'Запорізька обл.'), ('Ivano-frankivsk', 'Івано-Франківська обл.'), ('Kyiv', 'Київська обл.'), ('Kropyvnytskyi', 'Кіровоградська обл.'), ('Luhansk', 'Луганська обл.'), ('Lviv', 'Львівська обл.'), ('Mykolaiv', 'Миколаївська обл.'), ('Odesa', 'Одеська обл.'), ('Poltava', 'Полтавська обл.'), ('Rivne', 'Рівненська обл.'), ('Sumy', 'Сумська обл.'), ('Ternopil', 'Тернопільська обл.'), ('Kharkiv', 'Харківська обл.'), ('Kherson', 'Херсонська обл.'), ('Khmelnytskyi', 'Хмельницька обл.'), ('Cherkasy', 'Черкаська обл.'), ('Chernivtsi', 'Чернівецька обл.'), ('Chernihiv', 'Чернігівська обл.'), ('Simferopol', 'АР Крим')], max_length=255, verbose_name='Область')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.carmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.category')),
            ],
            options={
                'ordering': ['model'],
            },
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['model'], name='main_carmod_model_47b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['id', 'slug'], name='main_cars_id_bfcaef_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['model'], name='main_cars_model_i_9af7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['-created'], name='main_cars_created_d5508e_idx'),
        ),
    ]
