# Generated by Django 5.2.6 on 2025-09-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'Білий'), ('pearl_white', 'Перламутровий білий'), ('snow_white', 'Сніжно-білий'), ('arctic_white', 'Арктичний білий'), ('ivory_white', 'Молочний'), ('black', 'Чорний'), ('jet_black', 'Глибокий чорний'), ('obsidian_black', 'Обсидіановий чорний'), ('midnight_black', 'Опівнічний чорний'), ('phantom_black', 'Фантомний чорний'), ('gray', 'Сірий'), ('silver', 'Сріблястий'), ('gunmetal', 'Графітовий'), ('space_grey', 'Космічний сірий'), ('steel_grey', 'Стальний сірий'), ('charcoal', 'Антрацитовий'), ('blue', 'Синій'), ('navy_blue', 'Темно-синій'), ('deep_blue', 'Насичений синій'), ('light_blue', 'Блакитний'), ('sapphire_blue', 'Сапфіровий синій'), ('sky_blue', 'Небесно-блакитний'), ('red', 'Червоний'), ('bright_red', 'Яскраво-червоний'), ('burgundy', 'Бордовий'), ('wine_red', 'Винний червоний'), ('candy_red', 'Карамельний червоний'), ('crimson', 'Малиновий'), ('green', 'Зелений'), ('emerald_green', 'Смарагдовий зелений'), ('olive_green', 'Оливковий'), ('forest_green', 'Лісовий зелений'), ('dark_green', 'Темно-зелений'), ('yellow', 'Жовтий'), ('sport_yellow', 'Спортивний жовтий'), ('sunflower', 'Соняшниковий'), ('lemon', 'Лимонний'), ('mustard_yellow', 'Гірчичний жовтий'), ('orange', 'Помаранчевий'), ('burnt_orange', 'Вигорілий помаранчевий'), ('sunset_orange', 'Захід сонця'), ('copper', 'Мідний'), ('amber', 'Бурштиновий'), ('brown', 'Коричневий'), ('bronze', 'Бронзовий'), ('mocha', 'Мокко'), ('coffee_brown', 'Кавовий'), ('chocolate_brown', 'Шоколадний'), ('gold', 'Золотий'), ('champagne', 'Шампанське'), ('gold_metallic', 'Металік золото'), ('sand_gold', 'Піщано-золотий'), ('purple', 'Фіолетовий'), ('dark_purple', 'Темно-фіолетовий'), ('lavender', 'Лавандовий'), ('plum', 'Сливовий'), ('amethyst', 'Аметистовий'), ('pink', 'Рожевий'), ('hot_pink', 'Яскраво-рожевий'), ('light_pink', 'Ніжно-рожевий'), ('magenta', 'Малиново-рожевий'), ('fuchsia', 'Фуксія'), ('beige', 'Бежевий'), ('cream', 'Кремовий'), ('ivory', 'Слонова кістка'), ('sand', 'Піщаний'), ('khaki', 'Хакі'), ('matte_black', 'Матово-чорний'), ('matte_grey', 'Матово-сірий'), ('matte_blue', 'Матово-синій'), ('matte_red', 'Матово-червоний'), ('pearl', 'Перламутровий'), ('pearl_blue', 'Перламутровий синій'), ('pearl_green', 'Перламутровий зелений'), ('pearl_red', 'Перламутровий червоний'), ('chameleon', 'Хамелеон'), ('rainbow', 'Райдужний'), ('holographic', 'Голографічний')], max_length=255, null=True, verbose_name='Кольори'),
        ),
    ]
