# Generated by Django 5.2.6 on 2025-09-21 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carviews',
            unique_together={('car', 'ip_address'), ('car', 'user')},
        ),
    ]
