# Generated by Django 5.2.6 on 2025-09-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carviews',
            unique_together=set(),
        ),
    ]
