# Generated by Django 5.2.6 on 2025-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_carviews_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='type',
        ),
        migrations.AddField(
            model_name='cars',
            name='air_conditioner',
            field=models.CharField(blank=True, choices=[('ac', 'Кондиціонер'), ('climate_1', 'Клімат-контроль 1-зонний'), ('climate_2', 'Клімат-контроль 2-зонний'), ('climate_multi', 'Клімат-контроль багатозонний')], null=True, verbose_name='Кондиционеры'),
        ),
        migrations.AddField(
            model_name='cars',
            name='gearbox',
            field=models.CharField(blank=True, choices=[('manual', 'Механічна'), ('auto', 'Автоматична'), ('robot', 'Роботизована'), ('variator', 'Варіатор'), ('tiptronic', 'Типтронік')], null=True, verbose_name='Коробки передач'),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='used',
            field=models.BooleanField(blank=True, choices=[(True, 'Так'), (False, 'Ні')], null=True),
        ),
    ]
