# Generated by Django 5.2.6 on 2025-10-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMessages',
        ),
        migrations.DeleteModel(
            name='GroupName',
        ),
    ]
