REGIONS = [
    ("Vinnytsia", "Вінницька обл."),
    ("Lutsk", "Волинська обл."),
    ("Dnipro", "Дніпропетровська обл."),
    ("Donetsk", "Донецька обл."),
    ("Zhytomyr", "Житомирська обл."),
    ("Uzhhorod", "Закарпатська обл."),
    ("Zaporizhzhia", "Запорізька обл."),
    ("Ivano-frankivsk", "Івано-Франківська обл."),
    ("Kyiv", "Київська обл."),
    ("Kropyvnytskyi", "Кіровоградська обл."),
    ("Luhansk", "Луганська обл."),
    ("Lviv", "Львівська обл."),
    ("Mykolaiv", "Миколаївська обл."),
    ("Odesa", "Одеська обл."),
    ("Poltava", "Полтавська обл."),
    ("Rivne", "Рівненська обл."),
    ("Sumy", "Сумська обл."),
    ("Ternopil", "Тернопільська обл."),
    ("Kharkiv", "Харківська обл."),
    ("Kherson", "Херсонська обл."),
    ("Khmelnytskyi", "Хмельницька обл."),
    ("Cherkasy", "Черкаська обл."),
    ("Chernivtsi", "Чернівецька обл."),
    ("Chernihiv", "Чернігівська обл."),
    ("Simferopol", "АР Крим"),
]

TYPES=[
    ("Any", "Будь-який"),
    ("Cars", "Легкові"),
    ("Moto", "Мото"),
    ("Trucks", "Вантажівки"),
    ("Trailers", "Причепи"),
    ("Special", "Спецтехніка"),
    ("Agro", "Сільгосптехніка"),
    ("Buses", "Автобуси"),
    ("Water", "Водний транспорт"),
    ("Air", "Повітряний транспорт"),
    ("Campers", "Автобудинки"),
]

CAR_BRAND=[
  "Volkswagen",
  "Audi",
  "BMW",
  "Ford",
  "Renault",
  "Mercedes-Benz",
  "Nissan",
  "Skoda",
  "Opel",
  "Toyota",
  "Hyundai",
  "Mazda",
  "Kia",
  "Chevrolet",
  "Peugeot",
  "Mitsubishi",
  "Daewoo",
  "Honda",
  "ЗАЗ",
  "Jeep",
  "Citroen",
  "Lexus",
  "Volvo",
  "Land Rover",
  "Fiat",
  "Chery",
  "Infiniti",
  "Dodge",
  "Dacia",
  "Geely",
  "Porsche",
  "SEAT",
  "Jaguar",
  "MINI",
  "SsangYong",
  "Chrysler",
  "Acura",
  "Smart",
  "Lincoln",
  "УАЗ",
  "Alfa Romeo",
  "Cadillac",
  "BYD",
  "Great Wall",
  "Maserati",
  "Daihatsu",
  "MG",
  "Rover",
  "Lancia",
  "Bentley",
  "Hummer",
  "Isuzu",
  "Dadi",
  "Rolls-Royce",
  "Iveco",
  "Lamborghini",
  "Aston Martin",
  "Pontiac"
]

COLORS = [
    ("white", "Білий"),
    ("pearl_white", "Перламутровий білий"),
    ("snow_white", "Сніжно-білий"),
    ("arctic_white", "Арктичний білий"),
    ("ivory_white", "Молочний"),

    ("black", "Чорний"),
    ("jet_black", "Глибокий чорний"),
    ("obsidian_black", "Обсидіановий чорний"),
    ("midnight_black", "Опівнічний чорний"),
    ("phantom_black", "Фантомний чорний"),

    ("gray", "Сірий"),
    ("silver", "Сріблястий"),
    ("gunmetal", "Графітовий"),
    ("space_grey", "Космічний сірий"),
    ("steel_grey", "Стальний сірий"),
    ("charcoal", "Антрацитовий"),

    ("blue", "Синій"),
    ("navy_blue", "Темно-синій"),
    ("deep_blue", "Насичений синій"),
    ("light_blue", "Блакитний"),
    ("sapphire_blue", "Сапфіровий синій"),
    ("sky_blue", "Небесно-блакитний"),

    ("red", "Червоний"),
    ("bright_red", "Яскраво-червоний"),
    ("burgundy", "Бордовий"),
    ("wine_red", "Винний червоний"),
    ("candy_red", "Карамельний червоний"),
    ("crimson", "Малиновий"),

    ("green", "Зелений"),
    ("emerald_green", "Смарагдовий зелений"),
    ("olive_green", "Оливковий"),
    ("forest_green", "Лісовий зелений"),
    ("dark_green", "Темно-зелений"),

    ("yellow", "Жовтий"),
    ("sport_yellow", "Спортивний жовтий"),
    ("sunflower", "Соняшниковий"),
    ("lemon", "Лимонний"),
    ("mustard_yellow", "Гірчичний жовтий"),

    ("orange", "Помаранчевий"),
    ("burnt_orange", "Вигорілий помаранчевий"),
    ("sunset_orange", "Захід сонця"),
    ("copper", "Мідний"),
    ("amber", "Бурштиновий"),

    ("brown", "Коричневий"),
    ("bronze", "Бронзовий"),
    ("mocha", "Мокко"),
    ("coffee_brown", "Кавовий"),
    ("chocolate_brown", "Шоколадний"),

    ("gold", "Золотий"),
    ("champagne", "Шампанське"),
    ("gold_metallic", "Металік золото"),
    ("sand_gold", "Піщано-золотий"),

    ("purple", "Фіолетовий"),
    ("dark_purple", "Темно-фіолетовий"),
    ("lavender", "Лавандовий"),
    ("plum", "Сливовий"),
    ("amethyst", "Аметистовий"),

    ("pink", "Рожевий"),
    ("hot_pink", "Яскраво-рожевий"),
    ("light_pink", "Ніжно-рожевий"),
    ("magenta", "Малиново-рожевий"),
    ("fuchsia", "Фуксія"),

    ("beige", "Бежевий"),
    ("cream", "Кремовий"),
    ("ivory", "Слонова кістка"),
    ("sand", "Піщаний"),
    ("khaki", "Хакі"),

    ("matte_black", "Матово-чорний"),
    ("matte_grey", "Матово-сірий"),
    ("matte_blue", "Матово-синій"),
    ("matte_red", "Матово-червоний"),

    ("pearl", "Перламутровий"),
    ("pearl_blue", "Перламутровий синій"),
    ("pearl_green", "Перламутровий зелений"),
    ("pearl_red", "Перламутровий червоний"),

    ("chameleon", "Хамелеон"),
    ("rainbow", "Райдужний"),
    ("holographic", "Голографічний"),
]



CONDITIONERS = [
    ("ac", "Кондиціонер"),
    ("climate_1", "Клімат-контроль 1-зонний"),
    ("climate_2", "Клімат-контроль 2-зонний"),
    ("climate_multi", "Клімат-контроль багатозонний"),
]

GEARBOX = [
    ("manual", "Механічна"),
    ("auto", "Автоматична"),
    ("robot", "Роботизована"),
    ("variator", "Варіатор"),
    ("tiptronic", "Типтронік"),
]