REGIONS = [
    ("Vinnytsia", "Вінницька обл."),
    ("Lutsk", "Волинська обл."),
    ("Dnipro", "Дніпропетровська обл."),
    ("Donetsk", "Донецька обл."),
    ("Zhytomyr", "Житомирська обл."),
    ("Uzhhorod", "Закарпатська обл."),
    ("Zaporizhzhia", "Запорізька обл."),
    ("Ivano-frankivsk", "Івано-Франківська обл."),
    ("Kyiv", "Київська обл."),
    ("Kropyvnytskyi", "Кіровоградська обл."),
    ("Luhansk", "Луганська обл."),
    ("Lviv", "Львівська обл."),
    ("Mykolaiv", "Миколаївська обл."),
    ("Odesa", "Одеська обл."),
    ("Poltava", "Полтавська обл."),
    ("Rivne", "Рівненська обл."),
    ("Sumy", "Сумська обл."),
    ("Ternopil", "Тернопільська обл."),
    ("Kharkiv", "Харківська обл."),
    ("Kherson", "Херсонська обл."),
    ("Khmelnytskyi", "Хмельницька обл."),
    ("Cherkasy", "Черкаська обл."),
    ("Chernivtsi", "Чернівецька обл."),
    ("Chernihiv", "Чернігівська обл."),
    ("Simferopol", "АР Крим"),
]

TYPES=[
    ("Any", "Будь-який"),
    ("Cars", "Легкові"),
    ("Moto", "Мото"),
    ("Trucks", "Вантажівки"),
    ("Trailers", "Причепи"),
    ("Special", "Спецтехніка"),
    ("Agro", "Сільгосптехніка"),
    ("Buses", "Автобуси"),
    ("Water", "Водний транспорт"),
    ("Air", "Повітряний транспорт"),
    ("Campers", "Автобудинки"),
]

CAR_BRAND=[
  "Volkswagen",
  "Audi",
  "BMW",
  "Ford",
  "Renault",
  "Mercedes-Benz",
  "Nissan",
  "Skoda",
  "Opel",
  "Toyota",
  "Hyundai",
  "Mazda",
  "Kia",
  "Chevrolet",
  "Peugeot",
  "Mitsubishi",
  "Daewoo",
  "Honda",
  "ЗАЗ",
  "Jeep",
  "Citroen",
  "Lexus",
  "Volvo",
  "Land Rover",
  "Fiat",
  "Chery",
  "Infiniti",
  "Dodge",
  "Dacia",
  "Geely",
  "Porsche",
  "SEAT",
  "Jaguar",
  "MINI",
  "SsangYong",
  "Chrysler",
  "Acura",
  "Smart",
  "Lincoln",
  "УАЗ",
  "Alfa Romeo",
  "Cadillac",
  "BYD",
  "Great Wall",
  "Maserati",
  "Daihatsu",
  "MG",
  "Rover",
  "Lancia",
  "Bentley",
  "Hummer",
  "Isuzu",
  "Dadi",
  "Rolls-Royce",
  "Iveco",
  "Lamborghini",
  "Aston Martin",
  "Pontiac"
]